# Name of the workflow
name: Generate CSV-Ws from CSVs and qube configs
# How the workflow should be triggered.
on:
    push:
        branches:

# Workflow action
jobs:
    generate_csvw_from_csv_upload:
        name: Generate CSV-W from csv upload # generate_csvw_from_csv_upload job
        runs-on: ubuntu-latest
        steps:
          - name: csv-to-csvw action # csv-to-csvw action step
            # csv-to-csvw action path. The latest version is always available at https://github.com/marketplace/actions/csv-to-csvw-action
            uses: GSS-Cogs/csv-to-csvw-action@stash_issue
            # Configurations
            with:
                # Boolean indicating whether the outputs (i.e. out folder) should be committed to the current branch (default is true).
                commit-outputs-to-branch: true
                # Boolean indicating whether the outputs (i.e. out folder) should be published to the gh-pages branch and GitHub Pages (default is true).
                publish-to-gh-pages: true
                # File paths which csv-to-csvw should avoid converting into CSV-Ws
                # 1. This will ignore all files immediately in the `ignore` directory.
                # 2. This will recursively ignore all files in any subfolders of the `ignore` directory.
                paths-to-exclude: |
                    ignore/*
                    ignore/**/*
                # (WARNING: Advanced Configuration) Boolean indicating whether to only convert CSV files which have a companion JSON configuration file into CSV-Ws.
                config-required: false
                # (WARNING: Advanced Configuration) Boolean indicating whether to output debug statements in order to help diagnose a fault or unexpected behaviour.
                debug: false