# Name of the workflow
name: csv-to-csvw example
# How the workflow should be triggered.
on:
push:
    branches:
    - main # This workflow is triggered when committed to the main branch.
# Workflow action
jobs:
generate_csvw_from_csv_upload:
    name: Generate CSV-W from csv upload # generate_csvw_from_csv_upload job
    runs-on: ubuntu-latest
    steps:
        - name: csv-to-csvw action # csv-to-csvw action step
            # csv-to-csvw action path. The latest version is always available at https://github.com/marketplace/actions/csv-to-csvw-action
            uses: GSS-Cogs/csv-to-csvw-action@v0.0.31
            # Configurations
            with:
                # Boolean indicating whether the outputs (i.e. out folder) should be committed to the current branch (default is true).
                commit-outputs-to-branch: true
                # Boolean indicating whether the outputs (i.e. out folder) should be published to the gh-pages branch and GitHub Pages (default is true).
                publish-to-gh-pages: true
                # (WARNING: Advanced Configuration) Boolean indicating whether to only convert CSV files which have a companion JSON configuration file into CSV-Ws.
                config-required: true
